import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'

import ThemeProvider from '@/providers/ThemeProvider'
import { ClerkProvider } from '@clerk/nextjs'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

import { v2 as cloudinary } from 'cloudinary'
import { ProModal } from '@/components/ProModal'

cloudinary.config({
	cloud_name: process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
	api_key: process.env.NEXT_PUBLIC_CLOUDINARY_API_KEY,
	api_secret: process.env.NEXT_PUBLIC_CLOUDINARY_API_SECRET
})

export const metadata: Metadata = {
	title: 'Companion AI',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<ClerkProvider>
			<html lang="en" suppressHydrationWarning>
				<body className={cn('bg-secondary', inter.className)}>
					<ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
						<Toaster />
						<ProModal />
						{children}
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	)
}
